name: Build xg-140g-md
on: 
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      TZ: Asia/Shanghai
    steps:
      - name: Checkout Projects
        uses: actions/checkout@v2

      - name: Clean up the system
        run: |
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /usr/local/lib/android
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* adoptopenjdk* mysql* php* mongodb* dotnet* moby* snapd* || true
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

      - name: Installation depends
        run: |
          sudo apt update -y
          sudo apt full-upgrade -y
          sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
          bzip2 ccache clang cmake cpio curl device-tree-compiler ecj fastjar flex gawk gettext gcc-multilib \
          g++-multilib git gnutls-dev gperf haveged help2man intltool lib32gcc-s1 libc6-dev-i386 libelf-dev \
          libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses-dev libpython3-dev \
          libreadline-dev libssl-dev libtool libyaml-dev libz-dev lld llvm lrzsz mkisofs msmtp nano \
          ninja-build p7zip p7zip-full patch pkgconf python3 python3-pip python3-ply python3-docutils \
          python3-pyelftools qemu-utils re2c rsync scons squashfs-tools subversion swig texinfo uglifyjs \
          upx-ucl unzip vim wget xmlto xxd zlib1g-dev zstd

      - name: Clone source code
        run: |
          #wget https://github.com/openwrt/openwrt/archive/refs/tags/v25.12.2.tar.gz
          #tar -xzf v25.12.2.tar.gz && mv openwrt-25.12.2 openwrt
          #git clone https://github.com/openwrt/openwrt.git
          git clone -b openwrt-25.12-XG-040G-MD https://github.com/fzs209/immortalwrt.git openwrt
          cd openwrt/ && ./scripts/getver.sh

      - name: move .config
        run: |
          mv -f config/xg-040g-md.config openwrt/.config
          cd openwrt/
          #git fetch origin pull/21896/head:pr-21896
          #git checkout pr-21896
          #./scripts/getver.sh
          
          ls -l openwrt/.config || echo ".config NOT FOUND" && make defconfig

      - name: Cache OpenWrt build
        uses: actions/cache@v4
        with:
          path: |
            openwrt/dl
            openwrt/staging_dir
          key: openwrt-${{ runner.os }}-${{ hashFiles('openwrt/.config') }}
          restore-keys: |
            openwrt-${{ runner.os }}-

      - name: Download
        run: |
          ls -a $GITHUB_WORKSPACE

          cd openwrt/

          ./scripts/feeds update -a && ./scripts/feeds install -a

          ./scripts/feeds update -a && ./scripts/feeds install -a

          make -j $(nproc) download

      - name: Show config
        run: |
          cat openwrt/.config

      - name: target/linux prepare compile
        run: |
          cd openwrt/
          make -j $(nproc) target/linux/{clean,prepare} V=s

      - name: Build
        run: |
          cd openwrt/
          ./scripts/getver.sh

          make -j $(nproc) V=s
  
      - name: Set Date and Time
        id: datetime
        run: echo "::set-output name=datetime::$(date +'%Y%m%d%H%M%S')"

      - name: Upload openwrt firmware
        uses: softprops/action-gh-release@master
        with:
          tag_name: openwrt-xg-140g-md-${{ steps.datetime.outputs.datetime }}
          files: openwrt/bin/targets/airoha/an7581/*
          
